channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - graphviz=2.38.0
  - python=3.5.1
  - snakemake=5.1
  - pyyaml=3.11
  - r
  - biopython
  - jq
  - pytools
  - networkx
  - pygraphviz
  - curl
